---
title: "Chapter 8 Hypothesis Testing with Two Samples"
author: "Daxiang Na (那达翔)"
date: "2022-10-23"
CJKmainfont: STKaiti
output: 
  pdf_document: 
    includes:
        header-includes:
                - \usepackage{xeCJK}
    latex_engine: xelatex
    fig_caption: yes
    number_sections: yes
    toc: yes
  html_document:
    df_print: paged
    toc: yes
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, eval=T, tidy=TRUE, tidy.opts=list(width.cutoff=70))
library(tidyverse)
```

# Questions

## What is the sample size requirement for t tests?

# Comparison of Two Means

-   in Chapter 7, we talked about hypothesis test to compare the unknown mean of a single population to some fixed, known value, $\mu_{0}$

-   Often, we want to compare the means of two separate populations, where *both* means are unknown

-   \textcolor{red}{First step: determine whether the two samples are paired or independent.}

# Paired Samples

## Definition

-   for each observation in the first group, there is a corresponding observation in the second group

    -   Self-pairing: measurements are taken on a single subject at two distinct time points (before and after)
    -   Matched pairing: match two individuals with similar demographics/characteristics and compare their differences in response

## Procedure

### Parameters

- data: use the differences $d_{i} = b_{i} - a_{i}$ as the data

- Mean: the average of $d_{i}$ = $\bar{x}_{d}$

- Sample standard deviation of $d_{i}$ = $s_{d}$

- Standard error: $s_{d}/\sqrt{n}$

- Assumption: $\bar{x}_d \sim N\left(\mu_d, \sigma_d / \sqrt{n}\right)$

###

## Confidence Intervals

## R Code

## One-sided Paired t-test Example

# Independent Samples

## Equal, Known Variances

## Equal, Unknown Variances

## Unequal Variance (Welch t-test)
